Script started on 2025-04-05 00:29:11-04:00 [TERM="xterm-256color" TTY="/dev/pts/1" COLUMNS="68" LINES="32"]
[?2004hhabuzar@compute:~/courses/cs2211/Asn/asn5$ cat input.txt
[?2004lbba aa
aab aab
bba aa
aab abb
bba aaa
[?2004hhabuzar@compute:~/courses/cs2211/Asn/asn5$ ./mymatrix < input.txt
[?2004lString 1 String 2 Occurrence
aab        aab
                   1
aab        abb
                   1
bba         aa
                   2
bba        aaa
                   1
[?2004hhabuzar@compute:~/courses/cs2211/Asn/asn5$ end
[?2004lCommand 'end' not found, but there are 14 similar ones.
[?2004hhabuzar@compute:~/courses/cs2211/Asn/asn5$ ei[Kxit
[?2004lexit

Script done on 2025-04-05 00:29:39-04:00 [COMMAND_EXIT_CODE="127"]
