Script started on 2025-02-27 18:16:06-05:00 [TERM="xterm-256color" TTY="/dev/pts/52" COLUMNS="64" LINES="32"]
[?2004hhabuzar@compute:~/courses/cs2211/Asn/asn3$ ./ss_integer
[?2004lEnter a number (0-9):
0
 _ 
| |
|_|

Do you want to try again? (Y/N):
Y
Enter a number (0-9):
1
   
 | 
 | 

Do you want to try again? (Y/N):
Y
Enter a number (0-9):
2
 _ 
 _|
|_ 

Do you want to try again? (Y/N):
Y
Enter a number (0-9):
3
 _ 
 _|
 _|

Do you want to try again? (Y/N):
Y
Enter a number (0-9):
4
   
|_|
  |

Do you want to try again? (Y/N):
Y
Enter a number (0-9):
5
 _ 
|_ 
 _|

Do you want to try again? (Y/N):
Y
Enter a number (0-9):
6
 _ 
|_ 
|_|

Do you want to try again? (Y/N):
Y
Enter a number (0-9):
7
 _ 
  |
  |

Do you want to try again? (Y/N):
Y
Enter a number (0-9):
8
 _ 
|_|
|_|

Do you want to try again? (Y/N):
Y
Enter a number (0-9):
9
 _ 
|_|
 _|

Do you want to try again? (Y/N):
Y
Enter a number (0-9):
0
 _ 
| |
|_|

Do you want to try again? (Y/N):
N W Y
Enter a number (0-9):
R
Error: Out of Bounds.
[?2004hhabuzar@compute:~/courses/cs2211/Asn/asn3$ ./ss_integer
[?2004lEnter a number (0-9):
6
 _ 
|_ 
|_|

Do you want to try again? (Y/N):
U
Error: Incorrect input. Closing program. Goodbye
[?2004hhabuzar@compute:~/courses/cs2211/Asn/asn3$ ./ss_integer
[?2004lEnter a number (0-9):
5
 _ 
|_ 
 _|

Do you want to try again? (Y/N):
N
Closeing program. Goodbye!
[?2004hhabuzar@compute:~/courses/cs2211/Asn/asn3$ exit
[?2004lexit

Script done on 2025-02-27 18:17:01-05:00 [COMMAND_EXIT_CODE="0"]
