Script started on 2025-03-16 00:13:37-04:00 [TERM="xterm-256color" TTY="/dev/pts/2" COLUMNS="82" LINES="43"]
[?2004hhabuzar@compute:~/courses/cs2211/Asn/asn4$ ./bs_scrip[K[K[K[K[Ktree
[?2004l100, 1st Street, $1000
8, 3 Valleys Place, $2000
74, 3rd Street, $3000
4, 4 Oaks Crescent, $2100
10, Abbott Street, $2300
204, Beech Drive, $1800
36, Beechbank Crescent, $2400
36, Beechmount Crescent, $2500
46, Oxford Street, $2600
70, Oxford Street, $2500
101, Western Road, $2500
[?2004hhabuzar@compute:~/courses/cs2211/Asn/asn4$ end
[?2004lCommand 'end' not found, but there are 14 similar ones.
[?2004hhabuzar@compute:~/courses/cs2211/Asn/asn4$ exit
[?2004lexit

Script done on 2025-03-16 00:14:06-04:00 [COMMAND_EXIT_CODE="127"]
