Script started on 2025-03-16 00:14:18-04:00 [TERM="xterm-256color" TTY="/dev/pts/2" COLUMNS="82" LINES="43"]
[?2004hhabuzar@compute:~/courses/cs2211/Asn/asn4$ ./euler
[?2004lEnter number: 0.01
e = 1 + (1 / 1!) + (1 / 2!) + (1 / 3!) + (1 / 4!) = 2.7083333333
[?2004hhabuzar@compute:~/courses/cs2211/Asn/asn4$ ./euler
[?2004lEnter number: 0.000000000000000001
e = 1 + (1 / 1!) + (1 / 2!) + (1 / 3!) + (1 / 4!) + (1 / 5!) + (1 / 6!) + (1 / 7!) + (1 / 8!) + (1 / 9!) + (1 / 10!) + (1 / 11!) + (1 / 12!) + (1 / 13!) + (1 / 14!) + (1 / 15!) + (1 / 16!) = 2.7182818306
[?2004hhabuzar@compute:~/courses/cs2211/Asn/asn4$ ./euler
[?2004lEnter number: 0.00001
e = 1 + (1 / 1!) + (1 / 2!) + (1 / 3!) + (1 / 4!) + (1 / 5!) + (1 / 6!) + (1 / 7!) + (1 / 8!) = 2.7182787698
[?2004hhabuzar@compute:~/courses/cs2211/Asn/asn4$ ./euler
[?2004lEnter number: 4
e = 1 = 1.0000000000
[?2004hhabuzar@compute:~/courses/cs2211/Asn/asn4$ ./euler
[?2004lEnter number: -8
Please enter a positive limit.
[?2004hhabuzar@compute:~/courses/cs2211/Asn/asn4$ exit
[?2004lexit

Script done on 2025-03-16 00:15:02-04:00 [COMMAND_EXIT_CODE="1"]
